### PR TITLE
logrus: Drop this deprecated package

### PR DESCRIPTION
**Pull request by wking**
This package has been deprecated since the print package landed in 6fc7c2fc (#6).  Removing the logrus package makes it obvious that go-log/log consumers do not need to have a local copy of logrus (which is kind of the point of go-log/log ;), even if they use dependency tooling that does not support pruning unused subpackages.

I don't know what your thoughts on deprecation -> removal timescales are, but thought I'd file this so it's there whenever you want it ;).

Also, we still have the appengine sub-package with a non-stdlib dependency.  Thoughts about the https://github.com/go-logr/ approach where implementation shims go in sibling repositories (instead of subpackages)?

### CODE REVIEW

**Comment by asim** [comment]
Is it deprecated? Or is it just more appropriate for those that want obvious syntactic sugar for logrus related logging? I don't really know. I don't look at this log repo very often because I solved my own problem in a very simple manner. Any additions/changes are those brought from others trying to solve different problems. My assumption is that Print serves a certain purpose and to the contributor they understand how to use that with logrus but to external users its much easier to see a logrus package and use that.

Tim Hockins approach in go-logr is interesting. I guess appropriate where the github org is scoped to a specific requirement. We could potentially go down this route as well but any internal changes would then have to be propagated across the org.

What are your thoughts and motivations here?

**Comment by wking** [comment]
> Is it deprecated.

Yup, both of its public functions [document themselves as deprecated][1] an tell you how to upgrade to the more-generic `print` shim from #6.

> ... but to external users its much easier to see a logrus package and use that.

We already show the `print` approach to wrapping logrus in the README.  I'm open to other ways to increase discoverability.

> We could potentially go down this route as well but any internal changes would then have to be propagated across the org.

Hopefully there won't be any interface changes that need to be propagated.  But if there are, I'd hope they'll be rare.

> What are your thoughts and motivations here?

I want to make it as easy as possible to resolve misconceptions like [this][1].

[1]: https://github.com/emicklei/go-restful/pull/382#issuecomment-437652835
[1]: https://godoc.org/github.com/go-log/log/logrus

**Comment by asim** [comment]
I agree with your comments. Let's undertake the work to do this. I think the comment in the other thread is clear and resonates with me. Multiple dependencies that break in the long term kills adoption. The log repo should only have the log interface to minimize other dependencies for users and let them choose from other implementations we provide externally in the same form as logr.

If you agree and are willing to do the work I will add you as a maintainer to the org to do this.

**Comment by wking** [comment]
> If you agree and are willing to do the work I will add you as a maintainer to the org to do this.

Sounds good to me :).

**Comment by asim** [comment]
Cool. I have moved logrus functions here https://github.com/go-log/logrus just incase anyone does want them.

**Comment by wking** [comment]
> I'm not sure whether all should be moved or not. Thoughts? Is it things that are external dependencies beyond the stdlib or everything?

Only thing beyond the stdlib makes sense to me.  I doubt there are many potential consumers who'd care about a dead-code-for-them subpackage *and* not have pruning dependency tools.  And we can always revisit if folks like that turn up ;).

**Comment by asim** [comment]
SGTM

**Pull request merged**
